'use client';

import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { 
  AlertTriangle, 
  Scale, 
  FileText, 
  Clock, 
  Eye,
  Search, 
  Filter,
  Plus,
  Calendar,
  User,
  Gavel,
  History,
  Shield,
  Users,
  TrendingUp
} from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiGet, apiPost, apiPut, apiDelete, API_ENDPOINTS } from "@/config/api";
import { useAuth } from "@/context/AuthContext";

interface DisciplinaryAction {
  id: number;
  studentId: number;
  studentName?: string;
  actionDate: string;
  reason: string;
  status: 'ACTIVE' | 'RESOLVED' | 'APPEALED' | 'EXPIRED';
  outcome: string;
  createdAt: string;
  updatedAt: string;
}

interface DisciplinaryStats {
  totalCases: number;
  activeCases: number;
  resolvedCases: number;
  appealedCases: number;
  autoGeneratedCases: number;
}

interface Student {
  id: number;
  firstname: string;
  lastname: string;
  email: string;
}

export default function DisciplinePage() {
  const [disciplinaryActions, setDisciplinaryActions] = useState<DisciplinaryAction[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [stats, setStats] = useState<DisciplinaryStats>({
    totalCases: 0,
    activeCases: 0,
    resolvedCases: 0,
    appealedCases: 0,
    autoGeneratedCases: 0
  });
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [outcomeFilter, setOutcomeFilter] = useState("all");
  const [loading, setLoading] = useState(true);
  const [selectedAction, setSelectedAction] = useState<DisciplinaryAction | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [newAction, setNewAction] = useState({
    studentId: '',
    reason: '',
    outcome: 'conseil_1'
  });
  const { token } = useAuth();

  useEffect(() => {
    const fetchData = async () => {
      try {
        if (!token) return;
        
        // Fetch disciplinary actions and students in parallel
        const [actionsRes, studentsRes] = await Promise.all([
          apiGet(API_ENDPOINTS.DISCIPLINE, token),
          apiGet(API_ENDPOINTS.STUDENTS, token)
        ]);

        // Process disciplinary actions
        const actions = Array.isArray(actionsRes) ? actionsRes : [];
        const students = Array.isArray(studentsRes) ? studentsRes : [];
        
        // Add student names to disciplinary actions
        const actionsWithNames = actions.map((action: DisciplinaryAction) => {
          const student = students.find(s => s.id === action.studentId);
          return {
            ...action,
            studentName: student ? `${student.firstname} ${student.lastname}` : `Student ${action.studentId}`
          };
        });

        setDisciplinaryActions(actionsWithNames);
        setStudents(students);

        // Calculate stats
        const autoGenerated = actionsWithNames.filter(a => a.reason.includes('Excessive absences')).length;
        setStats({
          totalCases: actionsWithNames.length,
          activeCases: actionsWithNames.filter(a => a.status === 'ACTIVE').length,
          resolvedCases: actionsWithNames.filter(a => a.status === 'RESOLVED').length,
          appealedCases: actionsWithNames.filter(a => a.status === 'APPEALED').length,
          autoGeneratedCases: autoGenerated
        });

      } catch (error) {
        console.error("Error fetching disciplinary data:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
    const interval = setInterval(fetchData, 10000); // Poll every 10 seconds
    return () => clearInterval(interval);
  }, [token]);

  const handleCreateAction = async () => {
    if (!token || !newAction.studentId || !newAction.reason) return;
    
    try {
      const actionData = {
        studentId: parseInt(newAction.studentId),
        reason: newAction.reason,
        outcome: newAction.outcome,
        actionDate: new Date().toISOString().split('T')[0]
      };

      await apiPost(API_ENDPOINTS.DISCIPLINE, actionData, token);
      
      // Reset form and refresh data
      setNewAction({ studentId: '', reason: '', outcome: 'conseil_1' });
      setIsDialogOpen(false);
      
      // Refresh the data
      const actionsRes = await apiGet(API_ENDPOINTS.DISCIPLINE, token);
      const studentsRes = await apiGet(API_ENDPOINTS.STUDENTS, token);
      
      const actions = Array.isArray(actionsRes) ? actionsRes : [];
      const students = Array.isArray(studentsRes) ? studentsRes : [];
      
      const actionsWithNames = actions.map((action: DisciplinaryAction) => {
        const student = students.find(s => s.id === action.studentId);
        return {
          ...action,
          studentName: student ? `${student.firstname} ${student.lastname}` : `Student ${action.studentId}`
        };
      });

      setDisciplinaryActions(actionsWithNames);
    } catch (error) {
      console.error("Error creating disciplinary action:", error);
    }
  };

  const handleUpdateStatus = async (actionId: number, newStatus: string) => {
    if (!token) return;
    
    try {
      const action = disciplinaryActions.find(a => a.id === actionId);
      if (!action) return;

      const updateData = {
        ...action,
        status: newStatus
      };

      await apiPut(`${API_ENDPOINTS.DISCIPLINE}/${actionId}/status`, updateData, token);
      
      // Update locally
      setDisciplinaryActions(prev => 
        prev.map(a => 
          a.id === actionId 
            ? { ...a, status: newStatus as any }
            : a
        )
      );
    } catch (error) {
      console.error("Error updating disciplinary action:", error);
    }
  };

  const getOutcomeLabel = (outcome: string) => {
    switch (outcome) {
      case 'conseil_1': return 'First Warning';
      case 'conseil_2': return 'Second Warning';
      case 'conseil_3': return 'Final Warning';
      case 'aucune': return 'No Action';
      default: return outcome;
    }
  };

  const getOutcomeColor = (outcome: string) => {
    switch (outcome) {
      case 'conseil_1': return "bg-yellow-500/20 border-yellow-400/50 text-yellow-200";
      case 'conseil_2': return "bg-orange-500/20 border-orange-400/50 text-orange-200";
      case 'conseil_3': return "bg-red-500/20 border-red-400/50 text-red-200";
      case 'aucune': return "bg-gray-500/20 border-gray-400/50 text-gray-200";
      default: return "bg-gray-500/20 border-gray-400/50 text-gray-200";
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'ACTIVE': return "bg-red-500/20 border-red-400/50 text-red-200";
      case 'RESOLVED': return "bg-green-500/20 border-green-400/50 text-green-200";
      case 'APPEALED': return "bg-purple-500/20 border-purple-400/50 text-purple-200";
      case 'EXPIRED': return "bg-gray-500/20 border-gray-400/50 text-gray-200";
      default: return "bg-gray-500/20 border-gray-400/50 text-gray-200";
    }
  };

  const filteredActions = disciplinaryActions.filter(action => {
    const matchesSearch = action.studentName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         action.reason.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         action.studentId.toString().includes(searchTerm);
    const matchesStatus = statusFilter === "all" || action.status === statusFilter;
    const matchesOutcome = outcomeFilter === "all" || action.outcome === outcomeFilter;
    return matchesSearch && matchesStatus && matchesOutcome;
  });

  const ActionCard = ({ action }: { action: DisciplinaryAction }) => (
    <Card className="bg-white/80 backdrop-blur-md border-red-200 hover:border-red-300 transition-all duration-300 group shadow-lg">
      <CardContent className="p-6">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-red-500/20 border border-red-400/30">
              <AlertTriangle className="h-5 w-5 text-red-400" />
            </div>
            <div>
              <h3 className="font-semibold text-gray-900 group-hover:text-red-600 transition-colors">{action.studentName}</h3>
              <p className="text-sm text-gray-500">ID: {action.studentId}</p>
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <Badge className={`border ${getOutcomeColor(action.outcome)}`}>
              {getOutcomeLabel(action.outcome)}
            </Badge>
            <Badge className={`border ${getStatusColor(action.status)}`}>
              {action.status}
            </Badge>
          </div>
        </div>
        
        <div className="space-y-3">
          <div>
            <h4 className="text-sm font-medium text-red-600 mb-1">Reason</h4>
            <p className="text-gray-700">{action.reason}</p>
          </div>
          
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <span className="text-gray-500">Action Date:</span>
              <p className="text-gray-900 font-medium">{new Date(action.actionDate).toLocaleDateString()}</p>
            </div>
            <div>
              <span className="text-gray-500">Created:</span>
              <p className="text-gray-900 font-medium">{new Date(action.createdAt).toLocaleDateString()}</p>
            </div>
          </div>
        </div>
        
        <div className="flex gap-2 mt-6">
          <Button 
            size="sm" 
            variant="outline" 
            className="flex-1 border-red-400/30 hover:bg-red-500/20 text-red-600"
            onClick={() => setSelectedAction(action)}
          >
            <Eye className="h-3 w-3 mr-1" />
            Review
          </Button>
          {action.status === 'ACTIVE' && (
            <Button 
              size="sm" 
              className="bg-green-600/20 hover:bg-green-600/30 text-green-700 border border-green-500/30"
              onClick={() => handleUpdateStatus(action.id, 'RESOLVED')}
            >
              <Shield className="h-3 w-3 mr-1" />
              Resolve
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
      <div className="space-y-6 p-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-4xl font-bold bg-gradient-to-r from-red-600 via-orange-600 to-yellow-600 bg-clip-text text-transparent">
              Disciplinary Management
            </h1>
            <p className="text-slate-600 mt-2">Automated disciplinary actions based on attendance violations</p>
          </div>
          <div className="flex gap-3">
            <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
              <DialogTrigger asChild>
                <Button className="bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700 text-white shadow-lg shadow-red-500/20">
                  <Plus className="mr-2 h-4 w-4" />
                  New Action
                </Button>
              </DialogTrigger>
              <DialogContent className="bg-white/95 backdrop-blur-md border-red-500/30">
                <DialogHeader>
                  <DialogTitle className="text-red-700">Create Disciplinary Action</DialogTitle>
                  <DialogDescription className="text-slate-600">
                    Manually create a disciplinary action for a student
                  </DialogDescription>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <Label htmlFor="student" className="text-gray-700">Student</Label>
                    <Select value={newAction.studentId} onValueChange={(value) => setNewAction({...newAction, studentId: value})}>
                      <SelectTrigger className="bg-white border-gray-300 text-gray-900">
                        <SelectValue placeholder="Select student" />
                      </SelectTrigger>
                      <SelectContent className="bg-white border-gray-300">
                        {students.map((student) => (
                          <SelectItem key={student.id} value={student.id.toString()}>
                            {student.firstname} {student.lastname} ({student.email})
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="reason" className="text-gray-700">Reason</Label>
                    <Textarea 
                      id="reason" 
                      placeholder="Reason for disciplinary action" 
                      value={newAction.reason}
                      onChange={(e) => setNewAction({...newAction, reason: e.target.value})}
                      className="bg-white border-gray-300 text-gray-900 placeholder-gray-500"
                    />
                  </div>
                  <div>
                    <Label htmlFor="outcome" className="text-gray-700">Outcome</Label>
                    <Select value={newAction.outcome} onValueChange={(value) => setNewAction({...newAction, outcome: value})}>
                      <SelectTrigger className="bg-white border-gray-300 text-gray-900">
                        <SelectValue placeholder="Select outcome" />
                      </SelectTrigger>
                      <SelectContent className="bg-white border-gray-300">
                        <SelectItem value="conseil_1">First Warning</SelectItem>
                        <SelectItem value="conseil_2">Second Warning</SelectItem>
                        <SelectItem value="conseil_3">Final Warning</SelectItem>
                        <SelectItem value="aucune">No Action</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                  <Button 
                    onClick={handleCreateAction}
                    disabled={!newAction.studentId || !newAction.reason}
                    className="w-full bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700 disabled:opacity-50"
                  >
                    Create Action
                  </Button>
                </div>
              </DialogContent>
            </Dialog>
            <Button variant="outline" className="border-red-400 bg-red-50 text-red-700 hover:bg-red-100">
              <History className="mr-2 h-4 w-4" />
              Case History
            </Button>
          </div>
        </div>

        {/* Statistics Cards */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-6">
          <Card className="bg-white/80 backdrop-blur-md border-red-200 hover:border-red-300 transition-all duration-300 group shadow-lg">
            <CardContent className="p-6 text-center">
              <div className="relative">
                <Scale className="h-8 w-8 text-red-600 mx-auto mb-2 group-hover:scale-110 transition-transform" />
                <div className="absolute inset-0 bg-red-100 rounded-full blur-md opacity-0 group-hover:opacity-100 transition-opacity"></div>
              </div>
              <div className="text-2xl font-bold text-slate-800">{stats.totalCases}</div>
              <div className="text-sm text-red-600">Total Cases</div>
            </CardContent>
          </Card>

          <Card className="bg-white/80 backdrop-blur-md border-red-200 hover:border-red-300 transition-all duration-300 group shadow-lg">
            <CardContent className="p-6 text-center">
              <div className="relative">
                <AlertTriangle className="h-8 w-8 text-red-600 mx-auto mb-2 group-hover:scale-110 transition-transform" />
                <div className="absolute inset-0 bg-red-100 rounded-full blur-md opacity-0 group-hover:opacity-100 transition-opacity"></div>
              </div>
              <div className="text-2xl font-bold text-slate-800">{stats.activeCases}</div>
              <div className="text-sm text-red-600">Active</div>
            </CardContent>
          </Card>

          <Card className="bg-white/80 backdrop-blur-md border-green-200 hover:border-green-300 transition-all duration-300 group shadow-lg">
            <CardContent className="p-6 text-center">
              <div className="relative">
                <Shield className="h-8 w-8 text-green-600 mx-auto mb-2 group-hover:scale-110 transition-transform" />
                <div className="absolute inset-0 bg-green-100 rounded-full blur-md opacity-0 group-hover:opacity-100 transition-opacity"></div>
              </div>
              <div className="text-2xl font-bold text-slate-800">{stats.resolvedCases}</div>
              <div className="text-sm text-green-600">Resolved</div>
            </CardContent>
          </Card>

          <Card className="bg-white/80 backdrop-blur-md border-purple-200 hover:border-purple-300 transition-all duration-300 group shadow-lg">
            <CardContent className="p-6 text-center">
              <div className="relative">
                <Gavel className="h-8 w-8 text-purple-600 mx-auto mb-2 group-hover:scale-110 transition-transform" />
                <div className="absolute inset-0 bg-purple-100 rounded-full blur-md opacity-0 group-hover:opacity-100 transition-opacity"></div>
              </div>
              <div className="text-2xl font-bold text-slate-800">{stats.appealedCases}</div>
              <div className="text-sm text-purple-600">Appealed</div>
            </CardContent>
          </Card>

          <Card className="bg-white/80 backdrop-blur-md border-orange-200 hover:border-orange-300 transition-all duration-300 group shadow-lg">
            <CardContent className="p-6 text-center">
              <div className="relative">
                <TrendingUp className="h-8 w-8 text-orange-600 mx-auto mb-2 group-hover:scale-110 transition-transform" />
                <div className="absolute inset-0 bg-orange-100 rounded-full blur-md opacity-0 group-hover:opacity-100 transition-opacity"></div>
              </div>
              <div className="text-2xl font-bold text-slate-800">{stats.autoGeneratedCases}</div>
              <div className="text-sm text-orange-600">Auto-Generated</div>
            </CardContent>
          </Card>
        </div>

        {/* Search and Filter */}
        <Card className="bg-white/80 backdrop-blur-md border-red-200 shadow-lg">
          <CardContent className="p-4">
            <div className="flex flex-col sm:flex-row gap-4">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-2.5 h-4 w-4 text-red-500" />
                <Input
                  placeholder="Search cases by student, reason, or ID..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10 bg-white border-red-200 text-slate-800 placeholder-slate-500 focus:border-red-400"
                />
              </div>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger className="w-48 bg-white border-red-200 text-slate-800">
                  <SelectValue placeholder="Filter by status" />
                </SelectTrigger>
                <SelectContent className="bg-white border-red-200">
                  <SelectItem value="all">All Status</SelectItem>
                  <SelectItem value="ACTIVE">Active</SelectItem>
                  <SelectItem value="RESOLVED">Resolved</SelectItem>
                  <SelectItem value="APPEALED">Appealed</SelectItem>
                  <SelectItem value="EXPIRED">Expired</SelectItem>
                </SelectContent>
              </Select>
              <Select value={outcomeFilter} onValueChange={setOutcomeFilter}>
                <SelectTrigger className="w-48 bg-white border-red-200 text-slate-800">
                  <SelectValue placeholder="Filter by outcome" />
                </SelectTrigger>
                <SelectContent className="bg-white border-red-200">
                  <SelectItem value="all">All Outcomes</SelectItem>
                  <SelectItem value="conseil_1">First Warning</SelectItem>
                  <SelectItem value="conseil_2">Second Warning</SelectItem>
                  <SelectItem value="conseil_3">Final Warning</SelectItem>
                  <SelectItem value="aucune">No Action</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Cases Tabs */}
        <Tabs defaultValue="all" className="space-y-4">
          <TabsList className="bg-white/80 backdrop-blur-md border border-red-200">
            <TabsTrigger value="all" className="data-[state=active]:bg-red-500/30">All Cases</TabsTrigger>
            <TabsTrigger value="active" className="data-[state=active]:bg-red-500/30">Active</TabsTrigger>
            <TabsTrigger value="resolved" className="data-[state=active]:bg-green-500/30">Resolved</TabsTrigger>
            <TabsTrigger value="auto" className="data-[state=active]:bg-orange-500/30">Auto-Generated</TabsTrigger>
          </TabsList>

          <TabsContent value="all" className="space-y-4">
            {loading ? (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {[...Array(6)].map((_, i) => (
                  <div key={i} className="animate-pulse bg-white/50 backdrop-blur-md rounded-xl h-80 border border-red-200"></div>
                ))}
              </div>
            ) : filteredActions.length === 0 ? (
              <Card className="bg-white/80 backdrop-blur-md border-red-200">
                <CardContent className="flex flex-col items-center justify-center py-12">
                  <AlertTriangle className="h-12 w-12 text-red-400/50 mb-4" />
                  <h3 className="text-lg font-semibold text-slate-800 mb-2">No disciplinary cases found</h3>
                  <p className="text-slate-600 text-center mb-4">
                    {searchTerm ? "Try adjusting your search terms" : "No disciplinary actions have been recorded yet"}
                  </p>
                  <Button 
                    onClick={() => setIsDialogOpen(true)}
                    className="bg-gradient-to-r from-red-600 to-orange-600 hover:from-red-700 hover:to-orange-700"
                  >
                    <Plus className="mr-2 h-4 w-4" />
                    Create First Case
                  </Button>
                </CardContent>
              </Card>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredActions.map((action) => (
                  <ActionCard key={action.id} action={action} />
                ))}
              </div>
            )}
          </TabsContent>

          <TabsContent value="active" className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredActions.filter(a => a.status === 'ACTIVE').map((action) => (
                <ActionCard key={action.id} action={action} />
              ))}
            </div>
          </TabsContent>

          <TabsContent value="resolved" className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredActions.filter(a => a.status === 'RESOLVED').map((action) => (
                <ActionCard key={action.id} action={action} />
              ))}
            </div>
          </TabsContent>

          <TabsContent value="auto" className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filteredActions.filter(a => a.reason.includes('Excessive absences')).map((action) => (
                <ActionCard key={action.id} action={action} />
              ))}
            </div>
          </TabsContent>
        </Tabs>

        {/* Case Detail Dialog */}
        <Dialog open={!!selectedAction} onOpenChange={() => setSelectedAction(null)}>
          <DialogContent className="bg-white/95 backdrop-blur-md border-red-500/30 max-w-4xl">
            <DialogHeader>
              <DialogTitle className="text-red-700">Disciplinary Action Review</DialogTitle>
              <DialogDescription className="text-slate-600">
                Complete details for {selectedAction?.studentName}
              </DialogDescription>
            </DialogHeader>
            {selectedAction && (
              <div className="space-y-6">
                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <div>
                      <label className="text-sm text-gray-500">Student Information</label>
                      <div className="bg-gray-50 p-3 rounded-lg">
                        <p className="text-gray-900 font-medium">{selectedAction.studentName}</p>
                        <p className="text-gray-500 text-sm">ID: {selectedAction.studentId}</p>
                      </div>
                    </div>
                    <div>
                      <label className="text-sm text-gray-500">Outcome</label>
                      <Badge className={`${getOutcomeColor(selectedAction.outcome)} border`}>
                        {getOutcomeLabel(selectedAction.outcome)}
                      </Badge>
                    </div>
                    <div>
                      <label className="text-sm text-gray-500">Status</label>
                      <Badge className={`${getStatusColor(selectedAction.status)} border`}>
                        {selectedAction.status}
                      </Badge>
                    </div>
                  </div>
                  <div className="space-y-4">
                    <div>
                      <label className="text-sm text-gray-500">Action Date</label>
                      <p className="text-gray-900 font-medium">{new Date(selectedAction.actionDate).toLocaleDateString()}</p>
                    </div>
                    <div>
                      <label className="text-sm text-gray-500">Created</label>
                      <p className="text-gray-900 font-medium">{new Date(selectedAction.createdAt).toLocaleString()}</p>
                    </div>
                    <div>
                      <label className="text-sm text-gray-500">Last Updated</label>
                      <p className="text-gray-900 font-medium">{new Date(selectedAction.updatedAt).toLocaleString()}</p>
                    </div>
                  </div>
                </div>
                
                <div>
                  <label className="text-sm text-gray-500">Reason</label>
                  <div className="bg-gray-50 p-4 rounded-lg">
                    <p className="text-gray-900">{selectedAction.reason}</p>
                  </div>
                </div>
                
                <div className="flex gap-2 pt-4">
                  {selectedAction.status === 'ACTIVE' && (
                    <Button 
                      className="flex-1 bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800"
                      onClick={() => {
                        handleUpdateStatus(selectedAction.id, 'RESOLVED');
                        setSelectedAction(null);
                      }}
                    >
                      <Shield className="mr-2 h-4 w-4" />
                      Mark as Resolved
                    </Button>
                  )}
                  <Button variant="outline" className="flex-1 border-red-400/30 text-red-600 hover:bg-red-50">
                    <FileText className="mr-2 h-4 w-4" />
                    Generate Report
                  </Button>
                  <Button variant="outline" className="border-gray-400/30 text-gray-600 hover:bg-gray-50">
                    <History className="mr-2 h-4 w-4" />
                    View History
                  </Button>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}